version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd app
      - echo Installing source NPM dependencies ...
      - npm install
  build:
    commands:
      - echo Build started ..
      - npm run build

artifacts:
  files:
    - '**/*'
    #- "app/dist/**/*"
  base-directory: 'app/build'
  #discard-paths: yes